compute_components_flag: false
config_ar: !!python/object:neuralprophet.configure.AR
  ar_reg: null
  n_lags: 336
  reg_lambda: null
config_events: null
config_holidays: null
config_lagged_regressors: null
config_normalization: !!python/object:neuralprophet.configure.Normalization
  global_data_params: !!python/object/apply:collections.OrderedDict
  - - - ds
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: !!python/object/apply:pandas._libs.tslibs.timedeltas.Timedelta
        - 62362800000000000
        shift: !!python/object/apply:pandas._libs.tslibs.timestamps._unpickle_timestamp
        - 1467331200000000000
        - null
        - null
    - - y
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: !!python/object/apply:numpy.core.multiarray.scalar
        - &id001 !!python/object/apply:numpy.dtype
          args:
          - f8
          - false
          - true
          state: !!python/tuple
          - 3
          - <
          - null
          - null
          - null
          - -1
          - -1
          - 0
        - !!binary |
          LaMg9ZkVF0A=
        shift: !!python/object/apply:numpy.core.multiarray.scalar
        - *id001
        - !!binary |
          8lN2Pyk4EcA=
  global_normalization: false
  global_time_normalization: true
  local_data_params: !!python/object/apply:collections.OrderedDict
  - - - HUFL
      - !!python/object/apply:collections.OrderedDict
        - - - ds
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:pandas._libs.tslibs.timedeltas.Timedelta
              - 62362800000000000
              shift: !!python/object/apply:pandas._libs.tslibs.timestamps._unpickle_timestamp
              - 1467331200000000000
              - null
              - null
          - - y
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id001
              - !!binary |
                NRIPTvCuFUA=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id001
              - !!binary |
                fLmaZGMGEcA=
    - - HULL
      - !!python/object/apply:collections.OrderedDict
        - - - ds
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:pandas._libs.tslibs.timedeltas.Timedelta
              - 62362800000000000
              shift: !!python/object/apply:pandas._libs.tslibs.timestamps._unpickle_timestamp
              - 1467331200000000000
              - null
              - null
          - - y
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id001
              - !!binary |
                qOIvjYdVFEA=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id001
              - !!binary |
                z1UYltRpC8A=
    - - LUFL
      - !!python/object/apply:collections.OrderedDict
        - - - ds
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:pandas._libs.tslibs.timedeltas.Timedelta
              - 62362800000000000
              shift: !!python/object/apply:pandas._libs.tslibs.timestamps._unpickle_timestamp
              - 1467331200000000000
              - null
              - null
          - - y
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id001
              - !!binary |
                NAZXqw7eFUA=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id001
              - !!binary |
                qQkW18U5DcA=
    - - LULL
      - !!python/object/apply:collections.OrderedDict
        - - - ds
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:pandas._libs.tslibs.timedeltas.Timedelta
              - 62362800000000000
              shift: !!python/object/apply:pandas._libs.tslibs.timestamps._unpickle_timestamp
              - 1467331200000000000
              - null
              - null
          - - y
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id001
              - !!binary |
                BP+BwSqCE0A=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id001
              - !!binary |
                GNXxB5S6DcA=
    - - MUFL
      - !!python/object/apply:collections.OrderedDict
        - - - ds
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:pandas._libs.tslibs.timedeltas.Timedelta
              - 62362800000000000
              shift: !!python/object/apply:pandas._libs.tslibs.timestamps._unpickle_timestamp
              - 1467331200000000000
              - null
              - null
          - - y
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id001
              - !!binary |
                EOmLls5sFUA=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id001
              - !!binary |
                8lN2Pyk4EcA=
    - - MULL
      - !!python/object/apply:collections.OrderedDict
        - - - ds
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:pandas._libs.tslibs.timedeltas.Timedelta
              - 62362800000000000
              shift: !!python/object/apply:pandas._libs.tslibs.timestamps._unpickle_timestamp
              - 1467331200000000000
              - null
              - null
          - - y
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id001
              - !!binary |
                uS06pmpKFUA=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id001
              - !!binary |
                wou+xv0iDsA=
    - - OT
      - !!python/object/apply:collections.OrderedDict
        - - - ds
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:pandas._libs.tslibs.timedeltas.Timedelta
              - 62362800000000000
              shift: !!python/object/apply:pandas._libs.tslibs.timestamps._unpickle_timestamp
              - 1467331200000000000
              - null
              - null
          - - y
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id001
              - !!binary |
                nlzaEPqlEEA=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id001
              - !!binary |
                bWb889lAAMA=
  normalize: auto
  unknown_data_normalization: false
config_regressors: null
config_seasonality: null
config_train: !!python/object:neuralprophet.configure.Train
  batch_size: 128
  epochs: 55
  lambda_delay: 27
  learning_rate: 0.005
  loss_func: !!python/object:torch.nn.modules.loss.SmoothL1Loss
    _backward_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _buffers: !!python/object/apply:collections.OrderedDict
    - []
    _forward_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _is_full_backward_hook: null
    _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _modules: !!python/object/apply:collections.OrderedDict
    - []
    _non_persistent_buffers_set: !!set {}
    _parameters: !!python/object/apply:collections.OrderedDict
    - []
    _state_dict_hooks: !!python/object/apply:collections.OrderedDict
    - []
    beta: 1.0
    reduction: none
    training: true
  loss_func_name: SmoothL1Loss
  lr_finder_args: {}
  n_data: 118916
  newer_samples_start: 0.0
  newer_samples_weight: 2
  optimizer: !!python/name:torch.optim.adamw.AdamW ''
  optimizer_args:
    weight_decay: 0.001
  quantiles:
  - 0.5
  reg_delay_pct: 0.5
  reg_lambda_trend: null
  scheduler: !!python/name:torch.optim.lr_scheduler.OneCycleLR ''
  scheduler_args:
    anneal_strategy: cos
    div_factor: 100.0
    final_div_factor: 5000.0
    pct_start: 0.3
  trend_reg_threshold: false
config_trend: !!python/object:neuralprophet.configure.Trend
  changepoints: null
  changepoints_range: 0.8
  growth: 'off'
  n_changepoints: 0
  trend_global_local: global
  trend_reg: 0
  trend_reg_threshold: null
d_hidden: null
id_list:
- HUFL
- HULL
- LUFL
- LULL
- MUFL
- MULL
- OT
max_lags: 336
meta_used_in_model: false
metrics:
  MAE: !!python/object:torchmetrics.regression.mae.MeanAbsoluteError
    _backward_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _buffers: !!python/object/apply:collections.OrderedDict
    - []
    _cache: null
    _computed: null
    _defaults:
      sum_abs_error: !!python/object/apply:torch._utils._rebuild_tensor_v2
      - !!python/object/apply:torch.storage._load_from_bytes
        - !!binary |
          gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
          AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
          aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
          Z2UKcQFYDwAAADEwNTU1MzEzNjYxNTY2NHECWAMAAABjcHVxA0sBTnRxBFEugAJdcQBYDwAAADEw
          NTU1MzEzNjYxNTY2NHEBYS4BAAAAAAAAAAAAAAA=
      - 0
      - !!python/tuple []
      - !!python/tuple []
      - false
      - !!python/object/apply:collections.OrderedDict
        - []
      total: !!python/object/apply:torch._utils._rebuild_tensor_v2
      - !!python/object/apply:torch.storage._load_from_bytes
        - !!binary |
          gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
          AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
          aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApMb25nU3RvcmFn
          ZQpxAVgPAAAAMTA1NTUzMTM2NjE1OTA0cQJYAwAAAGNwdXEDSwFOdHEEUS6AAl1xAFgPAAAAMTA1
          NTUzMTM2NjE1OTA0cQFhLgEAAAAAAAAAAAAAAAAAAAA=
      - 0
      - !!python/tuple []
      - !!python/tuple []
      - false
      - !!python/object/apply:collections.OrderedDict
        - []
    _device: !!python/object/apply:torch.device
    - cpu
    _enable_grad: false
    _forward_cache: null
    _forward_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _is_full_backward_hook: null
    _is_synced: false
    _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _modules: !!python/object/apply:collections.OrderedDict
    - []
    _non_persistent_buffers_set: !!set {}
    _parameters: !!python/object/apply:collections.OrderedDict
    - []
    _persistent:
      sum_abs_error: false
      total: false
    _reductions:
      sum_abs_error: &id002 !!python/name:torchmetrics.utilities.data.dim_zero_sum ''
      total: *id002
    _should_unsync: true
    _state_dict_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _to_sync: true
    _update_count: 0
    compute_on_cpu: false
    dist_sync_fn: null
    dist_sync_on_step: false
    process_group: null
    sum_abs_error: !!python/object/apply:torch._utils._rebuild_tensor_v2
    - !!python/object/apply:torch.storage._load_from_bytes
      - !!binary |
        gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
        AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
        aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
        Z2UKcQFYDwAAADEwNTU1MzEzNjYxNTk4NHECWAMAAABjcHVxA0sBTnRxBFEugAJdcQBYDwAAADEw
        NTU1MzEzNjYxNTk4NHEBYS4BAAAAAAAAAAAAAAA=
    - 0
    - !!python/tuple []
    - !!python/tuple []
    - false
    - !!python/object/apply:collections.OrderedDict
      - []
    sync_on_compute: true
    total: !!python/object/apply:torch._utils._rebuild_tensor_v2
    - !!python/object/apply:torch.storage._load_from_bytes
      - !!binary |
        gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
        AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
        aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApMb25nU3RvcmFn
        ZQpxAVgPAAAAMTA1NTUzMTM2NjE2MDY0cQJYAwAAAGNwdXEDSwFOdHEEUS6AAl1xAFgPAAAAMTA1
        NTUzMTM2NjE2MDY0cQFhLgEAAAAAAAAAAAAAAAAAAAA=
    - 0
    - !!python/tuple []
    - !!python/tuple []
    - false
    - !!python/object/apply:collections.OrderedDict
      - []
    training: true
  RMSE: !!python/object:torchmetrics.regression.mse.MeanSquaredError
    _backward_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _buffers: !!python/object/apply:collections.OrderedDict
    - []
    _cache: null
    _computed: null
    _defaults:
      sum_squared_error: !!python/object/apply:torch._utils._rebuild_tensor_v2
      - !!python/object/apply:torch.storage._load_from_bytes
        - !!binary |
          gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
          AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
          aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
          Z2UKcQFYDwAAADEwNTU1MzEzNjYxNjE0NHECWAMAAABjcHVxA0sBTnRxBFEugAJdcQBYDwAAADEw
          NTU1MzEzNjYxNjE0NHEBYS4BAAAAAAAAAAAAAAA=
      - 0
      - !!python/tuple []
      - !!python/tuple []
      - false
      - !!python/object/apply:collections.OrderedDict
        - []
      total: !!python/object/apply:torch._utils._rebuild_tensor_v2
      - !!python/object/apply:torch.storage._load_from_bytes
        - !!binary |
          gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
          AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
          aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApMb25nU3RvcmFn
          ZQpxAVgPAAAAMTA1NTUzMTM2NjE2MjI0cQJYAwAAAGNwdXEDSwFOdHEEUS6AAl1xAFgPAAAAMTA1
          NTUzMTM2NjE2MjI0cQFhLgEAAAAAAAAAAAAAAAAAAAA=
      - 0
      - !!python/tuple []
      - !!python/tuple []
      - false
      - !!python/object/apply:collections.OrderedDict
        - []
    _device: !!python/object/apply:torch.device
    - cpu
    _enable_grad: false
    _forward_cache: null
    _forward_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _is_full_backward_hook: null
    _is_synced: false
    _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _modules: !!python/object/apply:collections.OrderedDict
    - []
    _non_persistent_buffers_set: !!set {}
    _parameters: !!python/object/apply:collections.OrderedDict
    - []
    _persistent:
      sum_squared_error: false
      total: false
    _reductions:
      sum_squared_error: *id002
      total: *id002
    _should_unsync: true
    _state_dict_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _to_sync: true
    _update_count: 0
    compute_on_cpu: false
    dist_sync_fn: null
    dist_sync_on_step: false
    process_group: null
    squared: false
    sum_squared_error: !!python/object/apply:torch._utils._rebuild_tensor_v2
    - !!python/object/apply:torch.storage._load_from_bytes
      - !!binary |
        gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
        AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
        aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
        Z2UKcQFYDwAAADEwNTU1MzEzNjYxNjMwNHECWAMAAABjcHVxA0sBTnRxBFEugAJdcQBYDwAAADEw
        NTU1MzEzNjYxNjMwNHEBYS4BAAAAAAAAAAAAAAA=
    - 0
    - !!python/tuple []
    - !!python/tuple []
    - false
    - !!python/object/apply:collections.OrderedDict
      - []
    sync_on_compute: true
    total: !!python/object/apply:torch._utils._rebuild_tensor_v2
    - !!python/object/apply:torch.storage._load_from_bytes
      - !!binary |
        gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
        AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
        aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApMb25nU3RvcmFn
        ZQpxAVgPAAAAMTA1NTUzMTM2NjE2Mzg0cQJYAwAAAGNwdXEDSwFOdHEEUS6AAl1xAFgPAAAAMTA1
        NTUzMTM2NjE2Mzg0cQFhLgEAAAAAAAAAAAAAAAAAAAA=
    - 0
    - !!python/tuple []
    - !!python/tuple []
    - false
    - !!python/object/apply:collections.OrderedDict
      - []
    training: true
n_forecasts: 1
n_lags: 336
num_hidden_layers: 0
num_seasonalities_modelled: 1
num_trends_modelled: 1
