compute_components_flag: false
config_ar: !!python/object:neuralprophet.configure.AR
  ar_reg: null
  n_lags: 336
  reg_lambda: null
config_events: null
config_holidays: null
config_lagged_regressors: null
config_normalization: !!python/object:neuralprophet.configure.Normalization
  global_data_params: !!python/object/apply:collections.OrderedDict
  - - - ds
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: !!python/object/apply:pandas._libs.tslibs.timedeltas.Timedelta
        - 31100400000000000
        shift: !!python/object/apply:pandas._libs.tslibs.timestamps._unpickle_timestamp
        - 1467331200000000000
        - null
        - null
    - - y
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: 1.0
        shift: 0.0
  global_normalization: false
  global_time_normalization: true
  local_data_params: !!python/object/apply:collections.OrderedDict
  - - - HUFL
      - !!python/object/apply:collections.OrderedDict
        - - - ds
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:pandas._libs.tslibs.timedeltas.Timedelta
              - 31100400000000000
              shift: !!python/object/apply:pandas._libs.tslibs.timestamps._unpickle_timestamp
              - 1467331200000000000
              - null
              - null
          - - y
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: 1.0
              shift: 0.0
    - - HULL
      - !!python/object/apply:collections.OrderedDict
        - - - ds
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:pandas._libs.tslibs.timedeltas.Timedelta
              - 31100400000000000
              shift: !!python/object/apply:pandas._libs.tslibs.timestamps._unpickle_timestamp
              - 1467331200000000000
              - null
              - null
          - - y
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: 1.0
              shift: 0.0
    - - LUFL
      - !!python/object/apply:collections.OrderedDict
        - - - ds
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:pandas._libs.tslibs.timedeltas.Timedelta
              - 31100400000000000
              shift: !!python/object/apply:pandas._libs.tslibs.timestamps._unpickle_timestamp
              - 1467331200000000000
              - null
              - null
          - - y
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: 1.0
              shift: 0.0
    - - LULL
      - !!python/object/apply:collections.OrderedDict
        - - - ds
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:pandas._libs.tslibs.timedeltas.Timedelta
              - 31100400000000000
              shift: !!python/object/apply:pandas._libs.tslibs.timestamps._unpickle_timestamp
              - 1467331200000000000
              - null
              - null
          - - y
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: 1.0
              shift: 0.0
    - - MUFL
      - !!python/object/apply:collections.OrderedDict
        - - - ds
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:pandas._libs.tslibs.timedeltas.Timedelta
              - 31100400000000000
              shift: !!python/object/apply:pandas._libs.tslibs.timestamps._unpickle_timestamp
              - 1467331200000000000
              - null
              - null
          - - y
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: 1.0
              shift: 0.0
    - - MULL
      - !!python/object/apply:collections.OrderedDict
        - - - ds
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:pandas._libs.tslibs.timedeltas.Timedelta
              - 31100400000000000
              shift: !!python/object/apply:pandas._libs.tslibs.timestamps._unpickle_timestamp
              - 1467331200000000000
              - null
              - null
          - - y
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: 1.0
              shift: 0.0
    - - OT
      - !!python/object/apply:collections.OrderedDict
        - - - ds
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:pandas._libs.tslibs.timedeltas.Timedelta
              - 31100400000000000
              shift: !!python/object/apply:pandas._libs.tslibs.timestamps._unpickle_timestamp
              - 1467331200000000000
              - null
              - null
          - - y
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: 1.0
              shift: 0.0
  normalize: 'off'
  unknown_data_normalization: false
config_regressors: null
config_seasonality: null
config_train: !!python/object:neuralprophet.configure.Train
  batch_size: 32
  epochs: 10
  lambda_delay: 5
  learning_rate: 0.005
  loss_func: !!python/object:torch.nn.modules.loss.MSELoss
    _backward_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _buffers: !!python/object/apply:collections.OrderedDict
    - []
    _forward_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _is_full_backward_hook: null
    _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _modules: !!python/object/apply:collections.OrderedDict
    - []
    _non_persistent_buffers_set: !!set {}
    _parameters: !!python/object/apply:collections.OrderedDict
    - []
    _state_dict_hooks: !!python/object/apply:collections.OrderedDict
    - []
    reduction: none
    training: true
  loss_func_name: MSELoss
  lr_finder_args: {}
  n_data: 58128
  newer_samples_start: 0.0
  newer_samples_weight: 2
  optimizer: !!python/name:torch.optim.adamw.AdamW ''
  optimizer_args:
    weight_decay: 0.001
  quantiles:
  - 0.5
  reg_delay_pct: 0.5
  reg_lambda_trend: null
  scheduler: !!python/name:torch.optim.lr_scheduler.OneCycleLR ''
  scheduler_args:
    anneal_strategy: cos
    div_factor: 100.0
    final_div_factor: 5000.0
    pct_start: 0.3
  trend_reg_threshold: false
config_trend: !!python/object:neuralprophet.configure.Trend
  changepoints: null
  changepoints_range: 0.8
  growth: 'off'
  n_changepoints: 0
  trend_global_local: global
  trend_reg: 0
  trend_reg_threshold: null
d_hidden: null
id_list:
- HUFL
- HULL
- MUFL
- MULL
- LUFL
- LULL
- OT
max_lags: 336
meta_used_in_model: false
metrics:
  MAE: !!python/object:torchmetrics.regression.mae.MeanAbsoluteError
    _backward_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _buffers: !!python/object/apply:collections.OrderedDict
    - []
    _cache: null
    _computed: null
    _defaults:
      sum_abs_error: !!python/object/apply:torch._utils._rebuild_tensor_v2
      - !!python/object/apply:torch.storage._load_from_bytes
        - !!binary |
          gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
          AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
          aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
          Z2UKcQFYDwAAADEwNTU1MzE3MjYxMzM5MnECWAMAAABjcHVxA0sBTnRxBFEugAJdcQBYDwAAADEw
          NTU1MzE3MjYxMzM5MnEBYS4BAAAAAAAAAAAAAAA=
      - 0
      - !!python/tuple []
      - !!python/tuple []
      - false
      - !!python/object/apply:collections.OrderedDict
        - []
      total: !!python/object/apply:torch._utils._rebuild_tensor_v2
      - !!python/object/apply:torch.storage._load_from_bytes
        - !!binary |
          gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
          AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
          aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApMb25nU3RvcmFn
          ZQpxAVgPAAAAMTA1NTUzMTcyNjE0MTkycQJYAwAAAGNwdXEDSwFOdHEEUS6AAl1xAFgPAAAAMTA1
          NTUzMTcyNjE0MTkycQFhLgEAAAAAAAAAAAAAAAAAAAA=
      - 0
      - !!python/tuple []
      - !!python/tuple []
      - false
      - !!python/object/apply:collections.OrderedDict
        - []
    _device: !!python/object/apply:torch.device
    - cpu
    _enable_grad: false
    _forward_cache: null
    _forward_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _is_full_backward_hook: null
    _is_synced: false
    _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _modules: !!python/object/apply:collections.OrderedDict
    - []
    _non_persistent_buffers_set: !!set {}
    _parameters: !!python/object/apply:collections.OrderedDict
    - []
    _persistent:
      sum_abs_error: false
      total: false
    _reductions:
      sum_abs_error: &id001 !!python/name:torchmetrics.utilities.data.dim_zero_sum ''
      total: *id001
    _should_unsync: true
    _state_dict_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _to_sync: true
    _update_count: 0
    compute_on_cpu: false
    dist_sync_fn: null
    dist_sync_on_step: false
    process_group: null
    sum_abs_error: !!python/object/apply:torch._utils._rebuild_tensor_v2
    - !!python/object/apply:torch.storage._load_from_bytes
      - !!binary |
        gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
        AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
        aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
        Z2UKcQFYDwAAADEwNTU1MzE3MjYxNDI3MnECWAMAAABjcHVxA0sBTnRxBFEugAJdcQBYDwAAADEw
        NTU1MzE3MjYxNDI3MnEBYS4BAAAAAAAAAAAAAAA=
    - 0
    - !!python/tuple []
    - !!python/tuple []
    - false
    - !!python/object/apply:collections.OrderedDict
      - []
    sync_on_compute: true
    total: !!python/object/apply:torch._utils._rebuild_tensor_v2
    - !!python/object/apply:torch.storage._load_from_bytes
      - !!binary |
        gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
        AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
        aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApMb25nU3RvcmFn
        ZQpxAVgPAAAAMTA1NTUzMTcyNjE0MzUycQJYAwAAAGNwdXEDSwFOdHEEUS6AAl1xAFgPAAAAMTA1
        NTUzMTcyNjE0MzUycQFhLgEAAAAAAAAAAAAAAAAAAAA=
    - 0
    - !!python/tuple []
    - !!python/tuple []
    - false
    - !!python/object/apply:collections.OrderedDict
      - []
    training: true
  RMSE: !!python/object:torchmetrics.regression.mse.MeanSquaredError
    _backward_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _buffers: !!python/object/apply:collections.OrderedDict
    - []
    _cache: null
    _computed: null
    _defaults:
      sum_squared_error: !!python/object/apply:torch._utils._rebuild_tensor_v2
      - !!python/object/apply:torch.storage._load_from_bytes
        - !!binary |
          gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
          AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
          aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
          Z2UKcQFYDwAAADEwNTU1MzE3MjYxNDExMnECWAMAAABjcHVxA0sBTnRxBFEugAJdcQBYDwAAADEw
          NTU1MzE3MjYxNDExMnEBYS4BAAAAAAAAAAAAAAA=
      - 0
      - !!python/tuple []
      - !!python/tuple []
      - false
      - !!python/object/apply:collections.OrderedDict
        - []
      total: !!python/object/apply:torch._utils._rebuild_tensor_v2
      - !!python/object/apply:torch.storage._load_from_bytes
        - !!binary |
          gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
          AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
          aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApMb25nU3RvcmFn
          ZQpxAVgPAAAAMTA1NTUzMTcyNjEzMTUycQJYAwAAAGNwdXEDSwFOdHEEUS6AAl1xAFgPAAAAMTA1
          NTUzMTcyNjEzMTUycQFhLgEAAAAAAAAAAAAAAAAAAAA=
      - 0
      - !!python/tuple []
      - !!python/tuple []
      - false
      - !!python/object/apply:collections.OrderedDict
        - []
    _device: !!python/object/apply:torch.device
    - cpu
    _enable_grad: false
    _forward_cache: null
    _forward_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _is_full_backward_hook: null
    _is_synced: false
    _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _modules: !!python/object/apply:collections.OrderedDict
    - []
    _non_persistent_buffers_set: !!set {}
    _parameters: !!python/object/apply:collections.OrderedDict
    - []
    _persistent:
      sum_squared_error: false
      total: false
    _reductions:
      sum_squared_error: *id001
      total: *id001
    _should_unsync: true
    _state_dict_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _to_sync: true
    _update_count: 0
    compute_on_cpu: false
    dist_sync_fn: null
    dist_sync_on_step: false
    process_group: null
    squared: false
    sum_squared_error: !!python/object/apply:torch._utils._rebuild_tensor_v2
    - !!python/object/apply:torch.storage._load_from_bytes
      - !!binary |
        gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
        AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
        aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
        Z2UKcQFYDwAAADEwNTU1MzE3MjYxMzIzMnECWAMAAABjcHVxA0sBTnRxBFEugAJdcQBYDwAAADEw
        NTU1MzE3MjYxMzIzMnEBYS4BAAAAAAAAAAAAAAA=
    - 0
    - !!python/tuple []
    - !!python/tuple []
    - false
    - !!python/object/apply:collections.OrderedDict
      - []
    sync_on_compute: true
    total: !!python/object/apply:torch._utils._rebuild_tensor_v2
    - !!python/object/apply:torch.storage._load_from_bytes
      - !!binary |
        gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
        AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
        aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApMb25nU3RvcmFn
        ZQpxAVgPAAAAMTA1NTUzMTcyNjEzNzEycQJYAwAAAGNwdXEDSwFOdHEEUS6AAl1xAFgPAAAAMTA1
        NTUzMTcyNjEzNzEycQFhLgEAAAAAAAAAAAAAAAAAAAA=
    - 0
    - !!python/tuple []
    - !!python/tuple []
    - false
    - !!python/object/apply:collections.OrderedDict
      - []
    training: true
n_forecasts: 1
n_lags: 336
num_hidden_layers: 0
num_seasonalities_modelled: 1
num_trends_modelled: 1
